language: java
jdk:
  - openjdk11
python:
  - "3.7"
#services:
#  - docker
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U wheel
  - sudo pip3 install -U virtualenvwrapper
install:
  - python3 -m pip install pipenv
script:
#  - docker-compose up -d
  - (cd scheduler/dev ; pipenv install --dev)
  - (cd scheduler/dev ; pipenv run pytest tests)
#  - ./gradlew test --tests "pl.diet.company.dietapp.TestAuthentication"
#  - ./gradlew test --tests "pl.diet.company.dietapp.TestProduct"
#  - ./gradlew test --tests "pl.diet.company.dietapp.TestAddProduct"
#  - ./gradlew test --tests "pl.diet.company.dietapp.TestProductRemove"
#  - ./gradlew test --tests "pl.diet.company.dietapp.unit.TestUserRegistration"
#  - ./gradlew test --tests "pl.diet.company.dietapp.TestUserRegistration"