version: "3.3"
services:
  mongo:
    container_name: diet_app_mongo
    build:
      context: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: diet_db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: diet_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: diet